services:
  securesign.web:
    build:
      context: .
      dockerfile: SecureSign.Web/Dockerfile
      target: base
    #labels:
    #   com.microsoft.visualstudio.debuggee.workingdirectory: "/app/build"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
    ports:
      - "5000"
    #  - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro